### ISSUE TITLE
callbackurl doesn't get called

### ISSUE THREAD

**Issue by anta66** [sapkotamadhusudan/rn-esewa#4]
i got proofOfPayment in mobile side but doesn't get any response in callbackurl.Any solutions?

**Comment by sapkotamadhusudan** [comment]
@anta66 Esewa team have to whitelist the callbackurl, please contact to esewa team with the callbackurl of your backend.
Only after that esewa backend will hit the provided callbackurl with proof of payment

**Comment by anta66** [comment]
okay will contact them..thank you
